# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import asset_upload_request_pb2 as asset__upload__request__pb2
from . import input_upload_request_pb2 as input__upload__request__pb2
from . import upload_status_pb2 as upload__status__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in file_push_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilePushServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadAsset = channel.stream_unary(
                '/norman.file_push.v2.FilePushService/UploadAsset',
                request_serializer=asset__upload__request__pb2.AssetUploadRequest.SerializeToString,
                response_deserializer=upload__status__pb2.UploadStatus.FromString,
                _registered_method=True)
        self.UploadInput = channel.stream_unary(
                '/norman.file_push.v2.FilePushService/UploadInput',
                request_serializer=input__upload__request__pb2.InputUploadRequest.SerializeToString,
                response_deserializer=upload__status__pb2.UploadStatus.FromString,
                _registered_method=True)


class FilePushServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadAsset(self, request_iterator, context):
        """Streams an asset file upload: first message is metadata, remaining are file chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadInput(self, request_iterator, context):
        """Streams an input file upload: first message is metadata, remaining are file chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilePushServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadAsset': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadAsset,
                    request_deserializer=asset__upload__request__pb2.AssetUploadRequest.FromString,
                    response_serializer=upload__status__pb2.UploadStatus.SerializeToString,
            ),
            'UploadInput': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadInput,
                    request_deserializer=input__upload__request__pb2.InputUploadRequest.FromString,
                    response_serializer=upload__status__pb2.UploadStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'norman.file_push.v2.FilePushService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('norman.file_push.v2.FilePushService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilePushService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadAsset(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/norman.file_push.v2.FilePushService/UploadAsset',
            asset__upload__request__pb2.AssetUploadRequest.SerializeToString,
            upload__status__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadInput(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/norman.file_push.v2.FilePushService/UploadInput',
            input__upload__request__pb2.InputUploadRequest.SerializeToString,
            upload__status__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
