# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_push.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_push.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import asset_upload_request_pb2 as asset__upload__request__pb2
from . import input_upload_request_pb2 as input__upload__request__pb2
from . import upload_status_pb2 as upload__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ile_push.proto\x12\x13norman.file_push.v2\x1a\x1a\x61sset_upload_request.proto\x1a\x1ainput_upload_request.proto\x1a\x13upload_status.proto2\xcb\x01\n\x0f\x46ilePushService\x12[\n\x0bUploadAsset\x12\'.norman.file_push.v2.AssetUploadRequest\x1a!.norman.file_push.v2.UploadStatus(\x01\x12[\n\x0bUploadInput\x12\'.norman.file_push.v2.InputUploadRequest\x1a!.norman.file_push.v2.UploadStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_push_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEPUSHSERVICE']._serialized_start=118
  _globals['_FILEPUSHSERVICE']._serialized_end=321
# @@protoc_insertion_point(module_scope)
