# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_push.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_push.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ile_push.proto\x12\x13norman.file_push.v2\"\x88\x01\n\x12\x41ssetUploadRequest\x12\x36\n\x08metadata\x18\x01 \x01(\x0b\x32\".norman.file_push.v2.AssetMetadataH\x00\x12/\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x1e.norman.file_push.v2.FileChunkH\x00\x42\t\n\x07payload\"\x88\x01\n\x12InputUploadRequest\x12\x36\n\x08metadata\x18\x01 \x01(\x0b\x32\".norman.file_push.v2.InputMetadataH\x00\x12/\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x1e.norman.file_push.v2.FileChunkH\x00\x42\t\n\x07payload\"w\n\rAssetMetadata\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x12\n\nversion_id\x18\x03 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x04 \x01(\t\x12\x1a\n\x12\x66ile_size_in_bytes\x18\x05 \x01(\x03\"\x8e\x01\n\rInputMetadata\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x12\n\nversion_id\x18\x03 \x01(\t\x12\x15\n\rinvocation_id\x18\x04 \x01(\t\x12\x10\n\x08input_id\x18\x05 \x01(\t\x12\x1a\n\x12\x66ile_size_in_bytes\x18\x06 \x01(\x03\"=\n\tFileChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x15\n\x08\x63hecksum\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_checksum\"b\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1c\n\x0fserver_checksum\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x12\n\x10_server_checksum2\xcb\x01\n\x0f\x46ilePushService\x12[\n\x0bUploadAsset\x12\'.norman.file_push.v2.AssetUploadRequest\x1a!.norman.file_push.v2.UploadStatus(\x01\x12[\n\x0bUploadInput\x12\'.norman.file_push.v2.InputUploadRequest\x1a!.norman.file_push.v2.UploadStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_push_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSETUPLOADREQUEST']._serialized_start=41
  _globals['_ASSETUPLOADREQUEST']._serialized_end=177
  _globals['_INPUTUPLOADREQUEST']._serialized_start=180
  _globals['_INPUTUPLOADREQUEST']._serialized_end=316
  _globals['_ASSETMETADATA']._serialized_start=318
  _globals['_ASSETMETADATA']._serialized_end=437
  _globals['_INPUTMETADATA']._serialized_start=440
  _globals['_INPUTMETADATA']._serialized_end=582
  _globals['_FILECHUNK']._serialized_start=584
  _globals['_FILECHUNK']._serialized_end=645
  _globals['_UPLOADSTATUS']._serialized_start=647
  _globals['_UPLOADSTATUS']._serialized_end=745
  _globals['_FILEPUSHSERVICE']._serialized_start=748
  _globals['_FILEPUSHSERVICE']._serialized_end=951
# @@protoc_insertion_point(module_scope)
