# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages/assets/asset_upload_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages/assets/asset_upload_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages.assets import asset_metadata_pb2 as messages_dot_assets_dot_asset__metadata__pb2
from messages.shared import file_chunk_pb2 as messages_dot_shared_dot_file__chunk__pb2
from messages.shared import upload_complete_pb2 as messages_dot_shared_dot_upload__complete__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*messages/assets/asset_upload_request.proto\x12\x13norman.file_push.v2\x1a$messages/assets/asset_metadata.proto\x1a messages/shared/file_chunk.proto\x1a%messages/shared/upload_complete.proto\"\xc1\x01\n\x12\x41ssetUploadRequest\x12\x36\n\x08metadata\x18\x01 \x01(\x0b\x32\".norman.file_push.v2.AssetMetadataH\x00\x12/\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x1e.norman.file_push.v2.FileChunkH\x00\x12\x37\n\x08\x63omplete\x18\x03 \x01(\x0b\x32#.norman.file_push.v2.UploadCompleteH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages.assets.asset_upload_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSETUPLOADREQUEST']._serialized_start=179
  _globals['_ASSETUPLOADREQUEST']._serialized_end=372
# @@protoc_insertion_point(module_scope)
