[build-system]
requires = ["flit_core==3.12.0"]
build-backend = "flit_core.buildapi"

[project]
name = "norman-core-sdk"
version = "0.1.0"
description = "Norman SDK"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "norman_objects @ git+https://github.com/norman-ml/norman_objects.git@development",
    "norman_utils_external @ git+https://github.com/norman-ml/norman_utils_external.git@86c6wa00a/tech-debt/sdk-tests",

    "aiofiles==24.1.0",
    "httpx==0.28.1",
    "xxhash==3.5.0"
]

[project.optional-dependencies]
dev = [
  "pytest==8.4.2",
  "pytest-asyncio==1.3.0"
]

[tool.flit.module]
name = "norman_core"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
testpaths = ["tests"]
markers = [
    "authenticate: anything to do with the authentication service",
    "file_pull: anything to do with the file_pull service",
    "file_push: anything to do with the file_push service",
    "persist: anything to do with the persist service",
    "retrieve: anything to do with the retrieve service",

    "accounts: anything to do with account entities",
    "models: anything to do with model entities",
    "invocations: anything to do with invocation entities"
]
