from typing import Optional

from norman_objects.shared.notifications.notification import Notification
from norman_objects.shared.queries.query_constraints import QueryConstraints
from norman_objects.shared.security.sensitive import Sensitive
from norman_utils_external.singleton import Singleton
from pydantic import TypeAdapter

from norman_core.clients.http_client import HttpClient


class Notifications(metaclass=Singleton):
    """
    Provides coroutine-based access to retrieve system or account-level
    notifications stored in the Norman persistence service.

    The `Notifications` class allows developers to query notifications
    generated by model executions, user actions, or system events.
    """

    def __init__(self) -> None:
        self._http_client = HttpClient()

    async def get_notifications(
        self,
        token: Sensitive[str],
        constraints: Optional[QueryConstraints] = None
    ) -> list[Notification]:
        """
        **Coroutine**

        Retrieve notifications that match the provided query constraints.

        This method fetches user, system, or model-related notifications
        from the Norman persistence layer, ordered and filtered
        according to the specified constraints.

        **Parameters**

        - ***token*** (`Sensitive[str]`) —
          Authentication token authorizing the request.

        - ***constraints*** (`Optional[QueryConstraints]`) —
          Optional query object for filtering, sorting, or limiting results.

          **Example Fields:**
          - `filters` (`dict`) — Filter notifications by type, severity, or status.
          - `limit` (`int`) — Maximum number of notifications to retrieve.
          - `offset` (`int`) — Number of notifications to skip for pagination.
          - `sort_by` (`str`) — Attribute used for sorting (e.g., `"created_at"`).
          - `descending` (`bool`) — Whether to sort results in descending order.

        **Response Structure**

        - ***response*** (`List[Notification]`) —
          A list of `Notification` objects matching the query.

          **Each `Notification` includes:**
          - **id** (`str`) — Unique identifier for the notification.
          - **type** (`str`) — Category of notification (e.g., `"system"`, `"execution"`, `"alert"`).
          - **message** (`str`) — Human-readable message or description.
          - **created_at** (`datetime`) — Timestamp when the notification was created.
          - **read** (`bool`) — Whether the notification has been read.

        **Example Usage:**
        ```python
        notifications_service = Notifications()

        # Retrieve the 10 most recent notifications
        constraints = QueryConstraints(limit=10, sort_by="created_at", descending=True)
        notifications = await notifications_service.get_notifications(token=my_token, constraints=constraints)

        for note in notifications:
            print(f"[{note.created_at}] {note.message}")
        ```
        """
        json = None
        if constraints is not None:
            json = constraints.model_dump(mode="json")

        response = await self._http_client.post("persist/notifications/get", token, json=json)
        return TypeAdapter(list[Notification]).validate_python(response)
